feature: duel timers for RPS
Monash-FIT3170/Shazam-3-Scrum-Unleashed pull request #125
Opened 2024-08-24 12:46 UTC by NameWasStolen

Added a duel timer that shows the remaining time for each duel.
This involved adding an extra DuelTimer,tsx overlay file, adding the extra type START_DUEL_TIMER, and adding the react + socket hooks and functions in rpsMatch, chooseAction and PlayerScreen.
Text scales with a smaller size depending on the mobile/computer screen. CSS of the text can be up for debate.

2024-08-24 13:00 UTC, fuzzylogic123 requested changes

2024-08-25 07:43 UTC, NameWasStolen commented on client/src/pages/PlayerScreen.tsx
> +    socket.on("START_DUEL_TIMER", (duelTime) => {
the logic for the other matchoverlay tsx files didnt have the logic included in the tsx file itself, so id leave it as is

2024-08-25 07:47 UTC, NameWasStolen commented on client/src/components/player-screen/match-overlay/DuelTimer.tsx
> +const DuelTimer = ({ time }: duelTimerProps) => {
issue is that with the current implementation of CountDownTimer, theres no way to abruptly stop it from ticking when used outside itself(i.e. in the example where both players pick their move early). the timerIntervalRef that i have in my implementation solves this.

2024-08-25 08:11 UTC, fuzzylogic123 approved these changes

2024-08-25 08:54 UTC, merged