Powerup/reverse paddle control
Monash-FIT3170/Shazam-3-Scrum-Unleashed pull request #174
Opened 2024-09-20 05:29 UTC by Suryadeep123

opponents paddle controls are reversed after power up is selected.

2024-09-25 13:47 UTC, fuzzylogic123 requested changes

2024-09-25 13:47 UTC, fuzzylogic123 commented on server/src/model/matches/pongMatch.ts
> +      console.log("Paddle 0 direction:", this.paddleStates[0].direction);
remove console logs

2024-09-26 05:32 UTC, fuzzylogic123 approved these changes

2024-09-26 05:33 UTC, Suryadeep123 commented on server/src/model/matches/pongMatch.ts
> +    if (!this.paddleStates[0].isReversedControl) {
sorted :)

2024-09-26 06:12 UTC, merged