Game ui2
Monash-FIT3170/Shazam-3-Scrum-Unleashed pull request #46
Opened 2024-05-11 02:12 UTC by YoMoM829

This pull request contains the UI for a Duel. This shows the buildup of a Duel, so the Rock, Paper and Shazam stages. This also shows the results of the Duel including the move both players made. Additionally, this UI is responsive to a mobile and desktop screen.

2024-05-11 03:24 UTC, RoryT-U commented
Please make sure your next branch uses the correct format and is slightly more descriptive (gameUI2 is that specific, something like feature/duel-ui would be good).

2024-05-11 03:26 UTC, RoryT-U commented on client/player.ts
The client should not have the entire Player class, I am assuming this is for testing purpose? Which if it is, make sure to remove if before you start a Pull Request.

2024-05-11 03:27 UTC, RoryT-U commented on client/src/App.tsx
I am assuming these changes were also for testing? If so please remove them back before sending PR.

2024-05-11 03:33 UTC, RoryT-U commented
There may be some issues either on my side or in the code with the how the UI is responsive. If a few other people can test it and see how if it works that would be good.
![image](https://github.com/Monash-FIT3170/Shazam-3-Scrum-Unleashed/assets/19358855/bc674ead-d263-4bdf-95fc-0ea2d5c5bd72)

2024-05-11 03:34 UTC, RoryT-U commented on client/src/components/DuelName.tsx
> +          </div>
Could potentially make these into components. Atleast atleast the inner part could be.

2024-05-11 03:35 UTC, RoryT-U commented on client/src/components/DuelScore.tsx
> +const duelScore = ({player1Score, player2Score, matchResult}: PlayerScoreProps) => {
Should be CamelCase (DuelScore)

2024-05-11 03:38 UTC, RoryT-U requested changes
Please have a look over the comments and make some appropriate changes.

2024-05-11 03:38 UTC, RoryT-U commented on client/src/components/DuelMove.tsx
> +const duelMove = ({type, win}: MoveProps) => {
Should be CamelCase

2024-05-11 03:38 UTC, RoryT-U commented on client/src/components/DuelLoad.tsx
> +const duelLoad = ({phase}: LoadProps) => {
Should be CamelCase

2024-05-11 05:20 UTC, lkog77 commented
> There may be some issues either on my side or in the code with the how the UI is responsive. If a few other people can test it and see how if it works that would be good. ![image](https://private-user-images.githubusercontent.com/19358855/329750439-bc674ead-d263-4bdf-95fc-0ea2d5c5bd72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDUwNzQsIm5iZiI6MTcxNTQwNDc3NCwicGF0aCI6Ii8xOTM1ODg1NS8zMjk3NTA0MzktYmM2NzRlYWQtZDI2My00YmRmLTk1ZmMtMGVhMmQ1YzViZDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA1MTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzN2RkNzRmN2ZhYjMyYTZiOTRhOTJmZjAzYmIyMmQ1ZGFhNzRmZWI5ODRmMWNjN2FlNTM0N2IwYWY4YWViNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6bPkRw4xCaqmDx8WQupRA8LWIb6Y1gD5TL-hhGhczwg)

Same

2024-05-12 07:39 UTC, RoryT-U commented
Please resolve issues that you fix, or add a comment if you disagree with what I said.

2024-05-12 08:52 UTC, YoMoM829 commented
Fixed previous errors. UI should be responsive to when a screen is minimised on a desktop and should be able to work on different screen sizes.

2024-05-12 09:02 UTC, YoMoM829 commented
I reviewed the changes and added the following corrections. Changes were much appreciated. I haven't added types yet since I want to see if the UIs we made can be combined. If so, we should incorporate them and then types. Also, adding types should not take long at all.

2024-05-12 09:08 UTC, YoMoM829 commented on client/player.ts
Yeah this is for testing sorry.

2024-05-12 09:09 UTC, YoMoM829 commented on client/src/App.tsx
I've changed it back so it should be fine.

2024-05-12 09:09 UTC, YoMoM829 commented on client/src/components/DuelMove.tsx
> +const duelMove = ({type, win}: MoveProps) => {
Yup done that

2024-05-12 09:09 UTC, YoMoM829 commented on client/src/components/DuelLoad.tsx
> +const duelLoad = ({phase}: LoadProps) => {
Yup changed that.

2024-05-12 09:20 UTC, RoryT-U commented on client/player.ts
Does it need to stay or can you delete it? Don't want people to accidently use it for anything.

2024-05-12 09:58 UTC, RoryT-U approved these changes

2024-05-12 10:01 UTC, merged